### ISSUE TITLE
manually edit  .as far as i know  cookie json exported by browser extension is not a fully valid conformant to cookie standard

### ISSUE THREAD

**Issue by woliu** [wanghaisheng/youtube-auto-upload#16]
manually edit  .as far as i know  cookie json exported by browser extension is not a fully valid conformant to cookie standard

_Originally posted by @wanghaisheng in https://github.com/wanghaisheng/youtube-auto-upload/issues/12#issuecomment-1120172509_

about the question,i want to know what do i need to do?

**Comment by wanghaisheng** [comment]
manually change no_restriction to

>        "sameSite": "None",

**Comment by woliu** [comment]
> manually change no_restriction to
> 
> > ```
> >    "sameSite": "None",
> > ```

hi，i found cookie.py have  'no_restriction'  i change no_restriction to None, but it don't work as well.

**Comment by woliu** [comment]
> Strict|Lax

i use Strict|Lax, it don't wort too.

**Comment by woliu** [comment]
in the eventing,i try it again, it works, thank yout
