### ISSUE TITLE
can this bypass the youtube upload limit?

### ISSUE THREAD

**Issue by sykeze** [wanghaisheng/youtube-auto-upload#20]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/wanghaisheng/youtube-auto-upload#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/wanghaisheng/youtube-auto-upload/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/wanghaisheng/youtube-auto-upload/issues?q=) for similar questions including closed ones

### Question

does this uploader (gui version specifically) bypass the youtube upload limit of 100 uploads per day? could it do 10k uploads in a day?

**Comment by wanghaisheng** [comment]
definitely not
it depends your account daily limit

**Comment by sykeze** [comment]
account daily limit is 100 for every account to ever exist on youtube. 

this is what you said

→ no limit of video counts
you may got hundreds of historical videos or prepare 200+ video for new product.

1000+ is possible especially for archive or backup usage as private

**Comment by wanghaisheng** [comment]
i dont say it can be done in 1 day though

other publish platform will limit monthly uploaded video count

**Comment by wanghaisheng** [comment]
if it can be done,definitely be flagged as spam and you lost your account ,that is not the price you want to pay
all of automation task are meant to act like human but ease your boring hand work

**Comment by sykeze** [comment]
just wanted to clarify whether or not it is possible.

**Comment by wanghaisheng** [comment]
I want to clarify that

bypasses API restrictions as I remember 

![image](https://user-images.githubusercontent.com/2363295/170888879-998e9177-09ed-4447-89b5-0c41318a0088.png)
