### ISSUE TITLE
how to get access non coding version i am already sponsoring 

### ISSUE THREAD

**Issue by simpelecase** [wanghaisheng/youtube-auto-upload#21]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/wanghaisheng/youtube-auto-upload#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/wanghaisheng/youtube-auto-upload/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/wanghaisheng/youtube-auto-upload/issues?q=) for similar questions including closed ones

### Question

how to get access non coding version i am already sponsoring

**Comment by wanghaisheng** [comment]
sorry  I would set up a contact info at readme

**Comment by simpelecase** [comment]
just sent email thanks
