### ISSUE TITLE
getting error on upload

### ISSUE THREAD

**Issue by simpelecase** [wanghaisheng/youtube-auto-upload#22]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/wanghaisheng/youtube-auto-upload#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/wanghaisheng/youtube-auto-upload/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/wanghaisheng/youtube-auto-upload/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

hey there i am getting this error on upload

**Comment by wanghaisheng** [comment]
no info ?

**Comment by simpelecase** [comment]
![ERROR](https://user-images.githubusercontent.com/105276415/171063692-3921a7a9-89b3-4e4c-b56a-0ab21ba2704e.png)

**Comment by wanghaisheng** [comment]
open any editor, edit cookie.json
replace 'no_restriction' to  None is fine

**Comment by simpelecase** [comment]
like this?

**Comment by simpelecase** [comment]
like this

**Comment by simpelecase** [comment]
![ERROR](https://user-images.githubusercontent.com/105276415/171064676-a4b23b5e-44bf-4195-8df7-8562ca2aa92c.png)

**Comment by wanghaisheng** [comment]
yeah

**Comment by simpelecase** [comment]
still same error

**Comment by wanghaisheng** [comment]
None instead none

**Comment by simpelecase** [comment]
working thanks

**Comment by wanghaisheng** [comment]
let me know

**Comment by simpelecase** [comment]
even putting 1 for policy its posting and videos private

**Comment by wanghaisheng** [comment]
can you paste the content of console

**Comment by simpelecase** [comment]
![image](https://user-images.githubusercontent.com/105276415/171068202-d11d00de-98e4-4728-b10d-0c55cb98302d.png)

**Comment by simpelecase** [comment]
stuck here

**Comment by wanghaisheng** [comment]
1.try to find 
   'this is a schedule video task'

**Comment by roxydoxyGits** [comment]
Hey, Wang! 
I am getting the exact sample Timeout 30000ms error as mentioned by @simpelecase Above.

It seems to be occurring whenever publishpolicy is 1. 

Is there a workaround? 

What do you mean by 1. try to find "this is a schedule task"?

**Comment by wanghaisheng** [comment]
I  need screen recording and full log for that 
for timeout issue 99% is caused by your network quality
for 1 it means publish at instant 
for 0 means private 
for 2 means publish at your schedule datetime

**Comment by roxydoxyGits** [comment]
Is there somewhere in your code you could change the timeout limits of a playwright page?
And I can not seem to upload a custom thumbnail. 
         ----The thumbnail file exists and I have the correct path to it 
         ----I did not make many changes to "one-file example. py" except for setting the path for video, cookie and thumbnail"  
               I left tags and description empty bc I have youtube upload default set.
               and turning | watcheverystep &   record screen to False

**Comment by roxydoxyGits** [comment]
Good to see you are still responsive,
many other people on github simply publish their git repo and forget about it after.

**Comment by wanghaisheng** [comment]
I need screen recording and full log for that
I really  did not intend to ask twice

**Comment by wanghaisheng** [comment]
1. try  uninstall using pip uninstall ytb_up
2. install at the root directory 
python setup.py install
3.run demo code

**Comment by roxydoxyGits** [comment]
I reinstalled Pip, so thumbnail part is working now. But program still times out, when publish policy is not 0
ScreenRecording: 
[d1db7ebc-21f2-416e-a102-0b9bfe91f2f7.webm](https://user-images.githubusercontent.com/108956972/178118757-409b2a44-1ed3-4848-8be5-38a9d4498aa9.webm)



Log:
 whether run in view mode True
start web page without proxy
DEBUG: Firefox is now running
============tags ['']
cookies existing C:\Users\maxxu\PycharmProjects\AgentRoxyProject\cookie.json
<Locator frame=<Frame name= url='https://www.youtube.com/'> selector='yt-img-shadow.ytd-topbar-menu-button-renderer > img:nth-child(1)'>
checking login status True
start change locale to english
Click your profile icon .
 Click Language or Location icon
choose the language or location you like to use.
finish change locale to english
DEBUG: Found YouTube upload Dialog Modal
DEBUG: Trying to upload "C:\Users\maxxu\PycharmProjects\AgentRoxyProject\Final.mp4" to YouTube...
DEBUG: Trying to detect verify...
there is no verification at all
DEBUG: Trying to set "[War Scene] The Japanese army fired planes to bomb the Chinese fleet ." as title...
click title field to input
clear existing title
filling new  title
DEBUG: Trying to set "[War Scene] The Japanese army fired planes to bomb the Chinese fleet ." as description...
DEBUG: Trying to set "C:\Users\maxxu\PycharmProjects\AgentRoxyProject\AgentRoxyThumbnail.png" as thumbnail...
DEBUG: Trying to set video to "Not made for kids"...
not made for kids task done
tags you give ['']
overwrite prefined channel tags 
click show more button
DEBUG: Trying to set "" as tags...
clear existing tags
filling new  tags
uploading progress check task done
next next!
next next!
next next!
DEBUG: Trying to set video visibility to public...

Error feed: 

Traceback (most recent call last):
  File "C:\Users\maxxu\PycharmProjects\AgentRoxyProject\GunKingDownload.py", line 345, in <module>
    task()
  File "C:\Users\maxxu\PycharmProjects\AgentRoxyProject\GunKingDownload.py", line 340, in task
    instantpublish()
  File "C:\Users\maxxu\PycharmProjects\AgentRoxyProject\GunKingDownload.py", line 249, in instantpublish
    asyncio.run(upload.upload(
  File "D:\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\maxxu\PycharmProjects\AgentRoxyProject\venv\lib\site-packages\ytb_up\youtube.py", line 401, in upload
    await page.locator(PUBLIC_RADIO_LABEL).click()
  File "C:\Users\maxxu\PycharmProjects\AgentRoxyProject\venv\lib\site-packages\playwright\async_api\_generated.py", line 12189, in click
    await self._impl_obj.click(
  File "C:\Users\maxxu\PycharmProjects\AgentRoxyProject\venv\lib\site-packages\playwright\_impl\_locator.py", line 144, in click
    return await self._frame.click(self._selector, strict=True, **params)
  File "C:\Users\maxxu\PycharmProjects\AgentRoxyProject\venv\lib\site-packages\playwright\_impl\_frame.py", line 474, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "C:\Users\maxxu\PycharmProjects\AgentRoxyProject\venv\lib\site-packages\playwright\_impl\_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\maxxu\PycharmProjects\AgentRoxyProject\venv\lib\site-packages\playwright\_impl\_connection.py", line 370, in _
    return await result
  File "C:\Users\maxxu\PycharmProjects\AgentRoxyProject\venv\lib\site-packages\playwright\_impl\_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "tp-yt-paper-radio-button.style-scope:nth-child(20)"
============================================================
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x00000288FEADD360>
Traceback (most recent call last):
  File "D:\lib\asyncio\base_subprocess.py", line 126, in __del__
  File "D:\lib\asyncio\base_subprocess.py", line 104, in close
  File "D:\lib\asyncio\proactor_events.py", line 108, in close
  File "D:\lib\asyncio\base_events.py", line 750, in call_soon
  File "D:\lib\asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000288FEADECB0>
Traceback (most recent call last):
  File "D:\lib\asyncio\proactor_events.py", line 116, in __del__
  File "D:\lib\asyncio\proactor_events.py", line 108, in close
  File "D:\lib\asyncio\base_events.py", line 750, in call_soon
  File "D:\lib\asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed

Process finished with exit code 1

**Comment by wanghaisheng** [comment]
@simpelecase 
18926010461  try add me
