### ISSUE TITLE
what is "has_cookies_for_current_website" method in driver object?

### ISSUE THREAD

**Issue by gghotted** [wanghaisheng/youtube-auto-upload#4]
when i execute Upload.upload,

occur error in upload.py line 95
`elif self.driver.has_cookies_for_current_website():`
AttributeError: 'Firefox' object has no attribute 'has_cookies_for_current_website'

what is "has_cookies_for_current_website" method in driver object?
and also i can not found "load_cookies" method in 96 line

**Comment by wanghaisheng** [comment]
pls  ignore these codes ,i double checked , it has no point at all
'''
 elif self.driver.has_cookies_for_current_website():

...
            self.driver.refresh()
'''
