### ISSUE TITLE
cannot find name=Public

### ISSUE THREAD

**Issue by bojkencako** [wanghaisheng/youtube-auto-upload#5]

**Comment by wanghaisheng** [comment]
pls  set headless flase and upload a screenrecording to help me debug

**Comment by bojkencako** [comment]
https://user-images.githubusercontent.com/43066683/156889316-5de290a2-1f8c-4198-892c-4e6febf93f3a.mp4

the title is wrong it doesnt delete that what is in the right,and for the thumbnail this channel is not verified thats why it doesnt go there,and it doesnt go to make account public but i might think the problem is at the title it gets longer because it doesnt erase the rest

**Comment by bojkencako** [comment]
i just removed len(text_fiel) and just putted 120 and now it works .it finds and the name=PUBLIC
        for _ in range(120):
            # more backspaces than needed just to be sure
            title_field.send_keys(Keys.BACKSPACE)
            sleep(0.1)

**Comment by wanghaisheng** [comment]
thanks for your input, you always can manually see what happens when headless is false and fix that 
you definitely pre-process meta-field to meet youtube all kinds of limits 
especially title,tags,description
