### ISSUE TITLE
it stuck at the next button it should have one more

### ISSUE THREAD

**Issue by bojkencako** [wanghaisheng/youtube-auto-upload#6]
did this under it is good?
        try:
            self.log.debug("Trying to set video visibility to public...")
            public_main_button = modal.find_element_by_name(PUBLIC_BUTTON)
            public_main_button.find_element_by_id(RADIO_LABEL).click()

        except:
            pass
        else:
            self.click_next(modal) #in here it click the next and the program continues
            self.log.debug("Trying to set video visibility to public...")
            public_main_button = modal.find_element_by_name(PUBLIC_BUTTON)
            public_main_button.find_element_by_id(RADIO_LABEL).click()

**Comment by bojkencako** [comment]
try:
            self.log.debug("Trying to set video visibility to public...")
            public_main_button = modal.find_element_by_name(PUBLIC_BUTTON)
            public_main_button.find_element_by_id(RADIO_LABEL).click()

        except:
            pass
        else:
            self.click_next(modal)
            self.log.debug("Trying to set video visibility to public...")
            public_main_button = modal.find_element_by_name(PUBLIC_BUTTON)
            public_main_button.find_element_by_id(RADIO_LABEL).click()

**Comment by wanghaisheng** [comment]
I have never encounter this case,what does it appears in browser?

**Comment by bojkencako** [comment]
My video was posted two times one times it didnt went public just draft second time it went public.because the second time it pressed all next ,in the first time it didnt only 2 times.to encounter this problem i did this code but i dont know if it is good for the program or not.

**Comment by wanghaisheng** [comment]
from my experience,there are  confirm steps after your publish setting,
if your video finished publish setting but failed to confirm button ,it will  go to draft.
can you do a screen video again for clarify

**Comment by bojkencako** [comment]
I worked 30 min uploaded 6 videos and i can see the title problem is not solved.thats why it cant go to the next because the title is longer than 100 characters.you can see the video where i posted for the name=public issue

**Comment by wanghaisheng** [comment]
do you fix this noww？

**Comment by bojkencako** [comment]
I added the loop te backspace the title two times.i dont know if it will happen again

**Comment by wanghaisheng** [comment]
i suggest you cal the title length and cut it before feed to autoupload method

**Comment by bojkencako** [comment]
i just went to the youtube account and select the default title and added 3 characters and now the program works
