### ISSUE TITLE
how to

### ISSUE THREAD

**Issue by susantha1995** [wanghaisheng/youtube-auto-upload#7]
hi, please can make a short how-to video or screenshots to install and use this script correctly? this is hard to understand beginners.

**Comment by wanghaisheng** [comment]
pls  do check my gui demo 
first line in readme

**Comment by wanghaisheng** [comment]
https://youtu.be/Sqj0uO9VCy4 @susantha1995

**Comment by susantha1995** [comment]
> https://youtu.be/Sqj0uO9VCy4 @susantha1995

thank you very much for your video.  I tried this one https://github.com/wanghaisheng/autovideo  but there is no any video uploaded. i followed all steps. please check the attached screenshot. I created a new profile on firefox and also added a cookie.json file. all added in GUI. but it didn't upload any video in my folder. 
please can you check the screenshot to check the problem here?
![Screenshot (78)](https://user-images.githubusercontent.com/64296393/157586242-89e2164a-1b86-4fc7-86f3-9d7d2c43661d.png)


thank you!

**Comment by wanghaisheng** [comment]
for video files you need prepare a video and thumbnail file
their name should be the same
and you should press the middle button to check whether they are in pair then press third button

**Comment by susantha1995** [comment]
> for video files you need prepare a video and thumbnail file their name should be the same and you should press the middle button to check whether they are in pair then press third button

I prepare videos in a folder and added them to gui. but I didn't add thumbnails because I'm planning to upload 20-30 videos once so I can't create thumbnails. so without add thumbnails can't I upload videos??

**Comment by wanghaisheng** [comment]
yes  video image should in pair
in this demo gui  you should prepare thumbnail   what i decribe is the logic behind this demo
you can edit for sure

**Comment by susantha1995** [comment]
can I hire you to build a custom bot?

**Comment by wanghaisheng** [comment]
mail me at whs860603@gmail.com
