### ISSUE TITLE
when internet is slow it goes title function and before the browser shows it

### ISSUE THREAD

**Issue by bojkencako** [wanghaisheng/youtube-auto-upload#8]
when internet is slow it goes to upload function it uploads but the internet doesnt goes fast and the title function occur .Because it doesnt find title the function is stopped and it goes like this again and again.i tried to delay the title function to occur by doing a sleep.(60) when it uploads the video but it still goes like this.can you provide a solution ?

**Comment by wanghaisheng** [comment]
i will look into it

**Comment by bojkencako** [comment]
slowing the proccess is the solution in theory but when i practise i dont know why it cant

**Comment by wanghaisheng** [comment]
i find before you say configure default title fix that?

**Comment by bojkencako** [comment]
What fix? The default title fixes the thing that the cursor couldnt erase words longer than 70 characters .

**Comment by bojkencako** [comment]
I think the solution of this is title =title if title else title.box.text should be removed and only apply title = title .
